LIBDRUM-991. Report errors to enclosing script
Modified EtdLoader to exit with a non-zero status code when an error
occurs in the processing.

Modified the "load-etd" script to capture the status code from the
EtdLoader and use it as its exit status.

Modified the "load-etd-nightly" script to print an error message and
continue to the next file (leaving the file with the error in the
"incoming" directory, instead of moving it to the "processed"
directory), and return an exit status.

Modified "script-main-wrapper" to capture exit status and modify
the email "Subject" line to include "- ERROR(S) OCCURRE" on a non-zero
exit status.

https://umd-dit.atlassian.net/browse/LIBDRUM-991

diff --git a/dspace/bin/script-mail-wrapper b/dspace/bin/script-mail-wrapper
--- a/dspace/bin/script-mail-wrapper
+++ b/dspace/bin/script-mail-wrapper
@@ -65,10 +65,24 @@ echo LOG_FILE_PATH=\'$LOG_FILE_PATH\'
 echo SCRIPT_ARGUMENTS=\'$@\'
 
 # Call the script being wrapped
-$SCRIPT "$@" 2>&1 | tee "$LOG_FILE_PATH" || true
+
+# Temporary file to store the exit code from the subshell
+EXIT_CODE_FILE=$(mktemp)
+{
+  $SCRIPT "$@"
+  echo $? > "$EXIT_CODE_FILE"
+} 2>&1 | tee "$LOG_FILE_PATH"
+
+SCRIPT_EXIT_CODE=$(cat "$EXIT_CODE_FILE")
+rm "$EXIT_CODE_FILE"
+
+SUBJECT_LIST="$SCRIPT_BASENAME: $SERVER_TYPE"
+if [ $SCRIPT_EXIT_CODE -ne 0 ]; then
+  SUBJECT_LIST="$SCRIPT_BASENAME: $SERVER_TYPE - ERROR(S) OCCURRED"
+fi
 
 # Mail the log, passing all non-JSON unchanged, and filtering out DEBUG messages
 jq -R -r '. as $line | try (fromjson | select(."log.level" != "DEBUG") | .message) catch $line' $LOG_FILE_PATH | \
-$MAIL_SCRIPT_DIR/mail -s "$SCRIPT_BASENAME: $SERVER_TYPE" "$EMAIL_ADDRESS"
+$MAIL_SCRIPT_DIR/mail -s "$SUBJECT_LIST" "$EMAIL_ADDRESS"
 
 echo Done running `basename $0` script
